name: Deploy Network Infrastructure

on:
  workflow_dispatch:

jobs:
  network:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_hostname: app.terraform.io
          cli_config_credentials_token: ${{ secrets.TF_CLOUD_TOKEN }}
          terraform_version: latest

      - name: Configure Scaleway CLI
        env:
          SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
          SCW_DEFAULT_PROJECT_ID: ${{ secrets.SCW_PROJECT_ID }}
          SCW_DEFAULT_ORGANIZATION_ID: ${{ secrets.SCW_ORGANIZATION_ID }}
          SCW_DEFAULT_REGION: fr-par
          SCW_DEFAULT_ZONE: fr-par-1
        run: |
          curl -s https://raw.githubusercontent.com/scaleway/scaleway-cli/master/scripts/get.sh | sh
          scw config set access-key "${SCW_ACCESS_KEY}"
          scw config set secret-key "${SCW_SECRET_KEY}"
          scw config set default-organization-id "${SCW_DEFAULT_ORGANIZATION_ID}"
          scw config set default-project-id "${SCW_DEFAULT_PROJECT_ID}"
          scw config set default-region "${SCW_DEFAULT_REGION}"
          scw config set default-zone "${SCW_DEFAULT_ZONE}"
