apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-soc-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: prometheus.my-soc.fr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prometheus-server
            port:
              number: 80
  - host: iris.my-soc.fr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: iriswebapp-app
            port:
              number: 8000
  - host: kibana.my-soc.fr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kibana-kibana
            port:
              number: 5601
  - host: demo.my-soc.fr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
