apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: doctobobo-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - doctobobo2.my-soc.fr
    # Rediriger HTTP vers HTTPS
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - doctobobo2.my-soc.fr
    tls:
      mode: SIMPLE
      credentialName: doctobobo-cert
