apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: doctobobo-cert
  namespace: istio-system
spec:
  secretName: doctobobo-tls
  issuerRef:
    name: letsencrypt-prod-istio
    kind: ClusterIssuer
  commonName: doctobobo2.my-soc.fr
  dnsNames:
  - doctobobo2.my-soc.fr
