apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: doctobobo
  namespace: istio-system
spec:
  gateways:
  - istio-system/doctobobo-gateway
  hosts:
  - doctobobo2.my-soc.fr
  http:
  - match:
    - uri:
        prefix: /.well-known/acme-challenge/
    route:
    - destination:
        host: cm-acme-http-solver.istio-system.svc.cluster.local
        port:
          number: 8089
