apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: doctobobo
  namespace: istio-system
spec:
  hosts:
    - doctobobo2.my-soc.fr
  http:
    - match:
        - uri:
            prefix: "/.well-known/acme-challenge/"
      route:
        - destination:
            host: doctobobo
            port:
              number: 80
