indexer:
  deployment:
    enabled: true

  selfcert:
    enabled: false

  replicas: 3

  service:
    httpPort: 9200
    transport: 9300
    metrics: 9600
    type: ClusterIP

  images:
    repository: wazuh/wazuh-indexer
    tag: "4.6.0"
    pullPolicy: IfNotPresent
    updateStrategy: RollingUpdate
    replicaCount: 3
    imagePullSecrets:
      enabled: false
      secret: {}
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 800m
        memory: 2Gi

  config:

  env:
    OPENSEARCH_JAVA_OPTS: "-Xms1g -Xmx1g -Dlog4j2.formatMsgNoLookups=true"
    CLUSTER_NAME: "wazuh"
    # NETWORK_HOST: "_eth0_"
    NETWORK_HOST: "0.0.0.0"
    HTTP_CORS_ENABLE: "false"
    ALLOW_DEMOCERTIFICATES: "false"
    # The minimum number of masters that will be able to form a quorum. This
    # should be (#masters / 2) + 1. Default is 2.
    NUMBER_OF_MASTERS: "3"
    DISABLE_INSTALL_DEMO_CONFIG: "true"
    DISCOVERY_SERVICE: "wazuh-sand-indexer-nodes"


  plugins: []

  storageSize: 50Gi
  storageClassName: gp2

# Kibana for elasticsearch with Wazuh plugins pre-installed
dashboard:
  deployment:
    enabled: true

  replicas: 1

  images:
    repository: wazuh/wazuh-dashboard
    tag: "4.6.0"
    pullPolicy: IfNotPresent
    updateStrategy: OnDelete
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 900m
        memory: 1Gi
  # with this you will be able to access kibana on http port instead of https
  # if you use Ambassador edgestack this is necessary becasue
  # with `true` route will close unexpectedly
  # when accessing via ambassador external url
  enable_ssl: false

  service:
    httpPort: 5601
    type: ClusterIP

  env:
    INDEXER_URL: https://wazuh-sand-indexer-rest
    WAZUH_API_URL: https://wazuh-manager-master-0.wazuh-sand-cluster
    WAZUH_API_HOST: wazuh-manager-master-0.wazuh-sand-cluster
serviceAccount:
  create: true
#  annotations:
#    eks.amazonaws.com/role-arn: arn:aws:iam::xxxxx:role/wazuh-test
wazuh:
  syslog_enable: true
  deployment:
    enabled: true
  master_replicas: 1
  worker_replicas: 2
  key: c98b62a9b6169ac5f67dae55ae4a9088
  images:
    repository: wazuh/wazuh-manager
    tag: "4.6.0"
    pullSecret: regcred
    resources:
      requests:
        cpu: 500m
        memory: 500Mi
      limits:
        cpu: 850m
        memory: 1Gi
    worker_resources:
      requests:
        cpu: 1000m
        memory: 1Gi
      limits:
        cpu: 1500m
        memory: 2Gi

  env:
    FILEBEAT_SSL_VERIFICATION_MODE: none

  service:
    # annotations:
    type: ClusterIP
    masterType: ClusterIP
    workerType: ClusterIP
    m_nodeType: master
    w_nodeType: worker
    ports:
      registration: 1515
      api: 55000
      wazuhInternal: 1516
      agentEvents: 1514


  storageSizeWorker: 50Gi
  storageClassNameWorker: gp2
  storageSizeMaster: 50Gi
  storageClassNameMaster: gp2

identifier:
#  clusterId: autogenerated
#  tenantId: autogenerated
#  tenantName: autogenerated
#  spaceId: autogenerated
#  spaceName: autogenerated
  appId: sand
  appName: wazuh

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  host: "wazuh.example.com"
