controller:
  replicaCount: 2

  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/scw-loadbalancer-use-hostname: "true"

  config:
    use-forwarded-headers: "true"
    compute-full-forwarded-for: "true"

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

  ingressClassResource:
    name: "nginx"
    enabled: true
    default: true
