name: Destroy Kubernetes Cluster on Scaleway

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        working-directory: ./infra
        env:
          TF_VAR_scw_access_key: ${{ secrets.SCW_ACCESS_KEY }}
          TF_VAR_scw_secret_key: ${{ secrets.SCW_SECRET_KEY }}
          TF_VAR_scw_project_id: ${{ secrets.SCW_PROJECT_ID }}
        run: terraform init

      - name: Destroy Kubernetes Cluster
        working-directory: ./infra
        env:
          TF_VAR_scw_access_key: ${{ secrets.SCW_ACCESS_KEY }}
          TF_VAR_scw_secret_key: ${{ secrets.SCW_SECRET_KEY }}
          TF_VAR_scw_project_id: ${{ secrets.SCW_PROJECT_ID }}
        run: |
          # Destroy each resource individually using -target
          terraform destroy -auto-approve -target=scaleway_k8s_pool.pool
          terraform destroy -auto-approve -target=scaleway_k8s_cluster.cluster
          terraform destroy -auto-approve -target=scaleway_lb.lb
          terraform destroy -auto-approve -target=scaleway_lb_ip.lb_ip
          terraform destroy -auto-approve -target=scaleway_vpc_private_network.pvn

