name: Deploy Network

on:
  workflow_dispatch:

jobs:
  deploy-network:
    runs-on: ubuntu-latest
    steps:
      # Étape 1 : Checkout du dépôt
      - name: Checkout repository
        uses: actions/checkout@v2

      # Étape 2 : Installer les outils nécessaires
      - name: Install dependencies
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh
          curl -s https://raw.githubusercontent.com/scaleway/scaleway-cli/master/scripts/get.sh | sh
          sudo apt-get update && sudo apt-get install -y python3 python3-pip
          pip3 install ovh

      - name: Debug secrets
        run: |
          echo "SCW_ACCESS_KEY: ${SCW_ACCESS_KEY:0:5}"
          echo "SCW_SECRET_KEY: ${SCW_SECRET_KEY:0:5}***"  # Montre seulement les 5 premiers caractères
          echo "SCW_PROJECT_ID: ${SCW_PROJECT_ID:0:5}"
          echo "SCW_ORGANIZATION_ID: ${SCW_ORGANIZATION_ID:0:5}"
        env:
          SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
          SCW_PROJECT_ID: ${{ secrets.SCW_PROJECT_ID }}
          SCW_ORGANIZATION_ID: ${{ secrets.SCW_ORGANIZATION_ID }}


      # Étape 3 : Configurer Scaleway CLI
      - name: Configure Scaleway CLI
        env:
          SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
          SCW_DEFAULT_PROJECT_ID: ${{ secrets.SCW_PROJECT_ID }}
          SCW_DEFAULT_ORGANIZATION_ID: ${{ secrets.SCW_ORGANIZATION_ID }}
          SCW_DEFAULT_REGION: fr-par
          SCW_DEFAULT_ZONE: fr-par-1
        run: |
          mkdir -p ~/.config/scw
          touch ~/.config/scw/config.yaml
          scw config set access-key="${SCW_ACCESS_KEY}"
          scw config set secret-key="${SCW_SECRET_KEY}"
          scw config set default-organization-id="${SCW_DEFAULT_ORGANIZATION_ID}"
          scw config set default-project-id="${SCW_PROJECT_ID}"
          scw config set default-region="${SCW_DEFAULT_REGION}"
          scw config set default-zone="${SCW_DEFAULT_ZONE}"

      # Étape 4 : Déployer les ressources Kubernetes
      - name: Deploy NGINX Ingress Controller
        run: |
          kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/cloud/deploy.yaml
          kubectl rollout status deployment/ingress-nginx-controller -n ingress-nginx

      - name: Deploy cert-manager
        run: |
          kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.11.0/cert-manager.yaml
          sleep 20

      - name: Deploy ClusterIssuer
        run: |
          kubectl apply -f ./Ingress/clusterIssuer.yaml -n default

      - name: Deploy Ingress
        run: |
          kubectl apply -f ./Ingress/network.yaml

      # Étape 5 : Récupérer l'IP du Load Balancer
      - name: Get Load Balancer IP
        id: get-lb-ip
        run: |
          lb_id=$(scw lb list name=k8s-cluster-lb project-id=${{ secrets.SCW_PROJECT_ID }} --output json | jq -r '.[0].id')
          if [[ -z "$lb_id" || "$lb_id" == "null" ]]; then
            echo "Error: Load Balancer ID not found."
            exit 1
          fi
          lb_ip=$(scw lb list project-id=${{ secrets.SCW_PROJECT_ID }} --output json | jq -r '.[0].ip')
          if [[ -z "$lb_ip" || "$lb_ip" == "null" ]]; then
            echo "Error: Load Balancer IP not found."
            exit 1
          fi
          echo "Load Balancer IP: $lb_ip"
          echo "lb_ip=$lb_ip" >> $GITHUB_ENV

      # Étape 6 : Mettre à jour les domaines OVH
      - name: Update OVH Domains
        env:
          OVH_APP_KEY: ${{ secrets.OVH_APP_KEY }}
          OVH_APP_SECRET: ${{ secrets.OVH_APP_SECRET }}
          OVH_CONSUMER_KEY: ${{ secrets.OVH_CONSUMER_KEY }}
          LB_IP: ${{ env.lb_ip }}
        run: |
          python3 ./scripts/update_ovh_domains.py --ip $LB_IP

