name: Deploy Helm Apps

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_hostname: app.terraform.io
          cli_config_credentials_token: ${{ secrets.TF_CLOUD_TOKEN }}
          terraform_version: latest

      - name: Install Helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh

      - name: Install Scaleway CLI
        run: |
          curl -s https://raw.githubusercontent.com/scaleway/scaleway-cli/master/scripts/get.sh | sh
          scw version

      # Initialize Scaleway CLI with explicit credentials and configuration
      - name: Configure Scaleway CLI
        env:
          SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
          SCW_ORGANIZATION_ID: ${{ secrets.SCW_ORGANIZATION_ID }}
          SCW_PROJECT_ID: ${{ secrets.SCW_PROJECT_ID }}
          SCW_DEFAULT_REGION: fr-par
          SCW_DEFAULT_ZONE: fr-par-1
        run: |
          scw init \
            --access-key "$SCW_ACCESS_KEY" \
            --secret-key "$SCW_SECRET_KEY" \
            --organization-id "$SCW_ORGANIZATION_ID" \
            --project-id "$SCW_PROJECT_ID" \
            --region "$SCW_DEFAULT_REGION" \
            --zone "$SCW_DEFAULT_ZONE" <<< "y"
          scw config get

      - name: Configure kubeconfig
        env:
          SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
          SCW_ORGANIZATION_ID: ${{ secrets.SCW_ORGANIZATION_ID }}
          SCW_PROJECT_ID: ${{ secrets.SCW_PROJECT_ID }}
        run: |
          mkdir -p ~/.kube
          # Retrieve the cluster ID using explicit project and organization ID
          cluster_id=$(scw k8s cluster list name=k8s-cluster \
            --organization-id=${{ secrets.SCW_ORGANIZATION_ID }} \
            --project-id=${{ secrets.SCW_PROJECT_ID }} \
            --output json | jq -r '.[0].id')
          if [[ -z "$cluster_id" || "$cluster_id" == "null" ]]; then
            echo "Error: Kubernetes cluster ID not found or is not valid."
            exit 1
          fi
          echo "Cluster ID: $cluster_id"
          # Download kubeconfig for the specified cluster ID
          scw k8s kubeconfig get "$cluster_id" --region=$SCW_DEFAULT_REGION > ~/.kube/config

      # Install Falco using Helm on the Kubernetes cluster
      - name: Deploy Falco with Helm
        run: |
          helm repo add falcosecurity https://falcosecurity.github.io/charts
          helm repo update
          helm install falco falcosecurity/falco --create-namespace --namespace falco
