name: Deploy Kubernetes Cluster on Scaleway

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        working-directory: ./infra
        env:
          TF_VAR_scw_access_key: ${{ secrets.SCW_ACCESS_KEY }}
          TF_VAR_scw_secret_key: ${{ secrets.SCW_SECRET_KEY }}
          TF_VAR_scw_project_id: ${{ secrets.SCW_PROJECT_ID }}
        run: |
          terraform init \
            -backend-config="access_key=${{ secrets.SCW_ACCESS_KEY }}" \
            -backend-config="secret_key=${{ secrets.SCW_SECRET_KEY }}" \
            -backend-config="bucket=your-s3-bucket-name" \
            -backend-config="endpoint=https://s3.fr-par.scw.cloud" \
            -backend-config="region=fr-par"

      - name: Terraform Plan
        working-directory: ./infra
        env:
          TF_VAR_scw_access_key: ${{ secrets.SCW_ACCESS_KEY }}
          TF_VAR_scw_secret_key: ${{ secrets.SCW_SECRET_KEY }}
          TF_VAR_scw_project_id: ${{ secrets.SCW_PROJECT_ID }}
          TF_LOG: DEBUG
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        working-directory: ./infra
        env:
          TF_VAR_scw_access_key: ${{ secrets.SCW_ACCESS_KEY }}
          TF_VAR_scw_secret_key: ${{ secrets.SCW_SECRET_KEY }}
          TF_VAR_scw_project_id: ${{ secrets.SCW_PROJECT_ID }}
          TF_LOG: DEBUG
        run: terraform apply -auto-approve tfplan
